### ISSUE TITLE
Finish the map design

### ISSUE THREAD

**Issue by Taipeek** [Taipeek/officemario#5]

**Comment by arunksu** [comment]
I think map design is done. Level 3 is finished now we just need to continue the game after the end of each level.

**Comment by Taipeek** [comment]
please fix the level ends in each level
`{
                 "height":128,
                 "id":19,
                 "name":"levelend1",
                 "rotation":0,
                 "type":"levelend",
                 "visible":true,
                 "width":96,
                 "x":6850,
                 "y":227
                },`
this is example for level one... 
we cant have the level end in tiles that are solid...
make them the same size 96x128 and place them somewhere in the middle of the finish line structure you made.
also make only one level end
otherwise it is working now
also be careful with the public path prefix in the json files

**Comment by svitaluc** [comment]
in the first level - the first map it's possible to walk on the roof of the building and you then get to a lower level roof (nearly at the end of the map where there is one office missing in a line of offices) and from that place you cannot go anywhere, the programmer gets stuck there. Would it be possible to add there a bar so that he can jump back?
+ perhaps if you could go through the levels and check that the programmer can get to majority of the places, few times it's not possible to get to some places at all

**Comment by arunksu** [comment]
@Taipeek @svitaluc both of these issues have been fixed now 👍 

Currently fixing `levelend` positions on level 2 and 3 as well.
